### ISSUE TITLE
Refactor:  User Roles and Permissions

### ISSUE THREAD

**Issue by mariafurqan** [ParaLogicTech/textile#112]
Manufacturing User/Coating User

Coating Order Permissions:
User can create manufacturing stock entries (Finish the coating orders)

Pretreatment Order Permissions:
User can process the pretreatment order (from the quick start stage to finish work orders)

**Comment by SaiFi0102** [comment]
Lets separate Roles based on textile order documents:

- Printing User - Create Print Order, Create Coating Order and Start Print Order
- Pretreatment User - Create Pretreatment Order and Start
- Coating User - Only process Coating Order

Lets discuss

**Comment by mariafurqan** [comment]
Print Sales User: Create and process print and coating orders (Discussion Pending).
Print Production User: Only process print orders and coating orders.

Pretreatment Sales User:  Create and process Pretreatment Orders
Pretreatment Production User: Only process pretreatment User
