### ISSUE TITLE
feat: Fabric Ledger Report

### ISSUE THREAD

**Issue by mariafurqan** [ParaLogicTech/textile#127]
Fabric Ledger (Customer's Fabric):

1. Customer Name 
2. Fabric Code
3. Fabric Name 
4.  Date 
5. Item Group
6. Warehouses and default search filters. 

Customer Fabric Receipt : This field refers to the stock entry document (Source Doctype) associated with the receipt of fabric by the customer.

Delivery of Fabric: This field pertains to the Delivery Challan document (Source Doctype) related to customer fabric delivery.

Wastage Adjustments: This field involves Stock Reconciliations (Source Doctype) for managing wastage adjustments. 

Print Fabric Rejection: This aspect involves tracking defective pieces during printing. (Source Doctype ??)

Fabric Process Waste: This field tracks waste during printing, such as 1-2 meters of fabric or areas with printing defects. It may also include calculating printing wastage percentage during production. (Source Doctype ??)

Rejection during packaging

![image](https://github.com/ParaLogicTech/textile/assets/58623315/2dfcc4f6-f189-4d4e-bf32-2a3ae271f384)

[xx Stock ledger\[1\].docx](https://github.com/ParaLogicTech/textile/files/14883552/xx.Stock.ledger.1.docx)

[Copy of Image Medium Silk Stock Ledger(1).xlsx](https://github.com/ParaLogicTech/textile/files/14883556/Copy.of.Image.Medium.Silk.Stock.Ledger.1.xlsx)

**Comment by SaiFi0102** [comment]
Add screenshots as well

**Comment by abid-omar** [comment]
Stock and wastage adjustments can be from these Doctypes\

Coating (actual plus calculated %)
Print (actual plus calculated %)
Packing (actual plus calculated %)

Similarly for Pretreatment orders
