### ISSUE TITLE
func: Add Square meters to fabrics

### ISSUE THREAD

**Issue by abid-omar** [ParaLogicTech/textile#17]
Item type fabric should have an UOM Conversion Factor to unit of area: Square meter (based on fabric width).

This will eventually be used in the BOM application which is related to both weight (GSM) and area (square meter). This will lead to more accurate consumption and thereby stock and costings.

Also for in reports, we should be able to see sales price or cost price per square meter.

**Comment by SaiFi0102** [comment]
Is this correct?
Conversion: 1m (Length) = 1m (Length) * (width_in_inch * 0.0254)m (Width)

For Example:
Width: 79inch / 2m
Conversion: 1m (Length) = 2sq.m (Area)
Conversion: 1sq.m (Area) = 0.5m (Length)


If cost is Rs 100/m length then cost per sq.meter would be calculated as Rs 50/sq.m

**Comment by abid-omar** [comment]
Correct
