### ISSUE TITLE
feat(Print Order): Process BOM based on fabric weight (and square meters)

### ISSUE THREAD

**Issue by abid-omar** [ParaLogicTech/textile#28]
**Problem:**

In the textile printing industry, certain items are consumed based on square-area (where fabric width and length are the input), and certain items are consumed based on fabric weight (where GSM, width and length are the input).

For example, printing inks are consumed per square-area, whereas bleaching chemicals are consumed per fabric weight.

The BOM is currently set up to consume items per linear-meter. Certain items to be consumed based on fabric weight, which will give greater accuracy in the stock usage. The BOM order will regardless be given in linear-meters.

Future: After this is implemented, and we have better historical data, we will start to consume items per square-area instead of per linear meter.

**Processes based on Weight:**

- Coating
- Softening
- Desizing
- Bleaching

**Solution:**

- Validate Fabric Item's Net Weight Per Unit before creating BOMs
- Add a "Consumption by Fabric Weight" Check field in Process/Process Component items so that Print Order / Pretreatment Order can determine which processes should be based on weight and which should be based on Meter
- Add a "Fabric Pickup %" Percent field in Fabric Items to act as a multiplier for BOM usage
- If any Process Item consumption is based on Fabric Weight then BOM Qty should be `(Fabric Net Weight Per Unit * Fabric Pickup % / 100) Grams` otherwise `1 Meter`
- Patch all old Design Items: Create a new BOM, set the new BOM as default and set all old BOMs as Inactive

**Comment by abid-omar** [comment]
Rename Softening process to "Finishing" (not sure)
Reason: Softening is one type of Finishing process, there can be others.

**Comment by abid-omar** [comment]
If Fabric Weight not given, or
if Fabric Pickup % is not given on the Item level,
use a default value that is editable by the Administrator in the Module Settings.

**Comment by SaiFi0102** [comment]
> If Fabric Weight not given, or if Fabric Pickup % is not given on the Item level, use a default value that is editable by the Administrator in the Module Settings.

I do not approve of this idea. User should set it explicitly to the fallback values rather than the system falling back to the default values silently in order to prevent unexpected behavior in the case the user forgets to enter data

**Comment by SaiFi0102** [comment]
> Rename Softening process to "Finishing" (not sure) Reason: Softening is one type of Finishing process, there can be others.

Sounds reasonable

**Comment by abid-omar** [comment]
Ok.

**Comment by SaiFi0102** [comment]
@abid-omar 
- Is Fabric Pickup % the same for all processes for one Fabric?
- Does Fabric Pickup % change after pretreatment?
- Are we expecting most fabrics to have 100% pickup?

**Comment by abid-omar** [comment]
1. Generally same, but can vary
2. Does not change
3. Generally 100%

The target Pickup is 100%, but for certain fabrics at certain steps can vary.
