### ISSUE TITLE
feat: Create Pretreatment Order DocType

### ISSUE THREAD

**Issue by SaiFi0102** [ParaLogicTech/textile#47]
## Pretreatment Order

Pretreatment Order converts one Greige Fabric to one Ready Fabric by Singeing, Bleaching and Desizing the Greige Fabric.

## Notes

- Pretreatment Order converts one Greige Fabric to one Ready Fabric
- Both Greige Fabric and Ready Fabric must be created by user before submitting the Order
- Ready Fabric BOM creation will be the responsibility of Pretreatment Order
- Pretreatment Order will not handle Customer Fabric Receipts
- Greige Fabric Qty (Input Qty) and Ready Fabric Qty (Output Qty) does not change (aside from a very small process loss)
- Greige Fabric and Ready Fabric must have the same Fabric Material and Fabric Type
- Greige Fabric and Ready Fabric may have different Width and GSM/Weight
- Delivery/Packing is optional after production (since produced items may be used in printing)
- In case delivery is not required, then Sales Order needs to be configured to skip delivery note
- Singeing and Desizing is optional, Bleaching is mandatory
- Ready Fabric Item will have link to one Greige Fabric Item (Greige Fabric may have multiple Ready Fabrics)
- Ready Fabric's link to Greige Fabric may be changed in the future, however, the old transactions will keep reference to the old Greige Fabric
- Work Order should be independent of Sales Order (since Sales Order may also be optional in internal production cases)

## Fields

**First Section**

- Customer / Customer Name
- Order Date (`transaction_date`)
- Planned Delivery Date (`delivery_date`)
- Customer Purchase Order Reference / Date (`po_no`, `po_date`)
- Notes (`notes`)
- Delivery Required? (Allowed after submit, cannot change if any submitted packing slip or delivery note exists)
- Packing Slip Required for Delivery?

**Fabric Details Section**

- Greige Fabric Item / Name (`greige_fabric_item`, `greige_fabric_item_name`)
- Ready Fabric Item / Name (`ready_fabric_item`, `ready_fabric_item_name`, to be auto selected if only one)
- Fabric Material / Type (`fabric_material`, `fabric_type` to be fetched from `greige_fabric_item`)
- Greige Fabric Width / GSM (`greige_fabric_width`, `greige_fabric_gsm`)
- Greige Fabric Stock Qty (`greige_fabric_stock_qty`)
- Ready Fabric BOM (`ready_fabric_bom`, read only / no copy to be set by system)

**Qty Section**

- Qty (`qty`)
- UOM (`uom`, either Meter or Yard, fetched from Customer Defaults)
- Conversion Factor (`conversion_factor`, hidden)
- Stock Qty / Stock UOM (`stock_qty`, `stock_uom`, for Meters)

**Process Details Section**

- Bleaching Item / Name (`bleaching_item`, `bleaching_item_name`)
- Singeing Item / Name (`singeing_item`, `singeing_item_name`)
- Desizing Item / Name (`desizing_item`, `desizing_item_name`)

**Warehouse Section (Collapsed)**

- Raw Material Warehouse (`source_warehouse`, auto set from settings/global defaults)
- Work In Progress Warehouse (`wip_warehouse`, auto set from settings/global defaults)
- Finished Goods Warehouse (`fg_warehouse`, auto set from settings/global defaults)

**Status Tab**
- Status (`status`) [Draft, Not Started, In Production, To Deliver?, Completed, Closed, Cancelled]
- Ordered Qty (`ordered_qty`)
- Work Order Qty (`work_order_qty`)
- Produced Qty (`produced_qty`)
- Production Status (`production_status`) [To Produce, Produced, Not Applicable]
- Packing Status (`packing_status`) [To Pack, Packed, Not Applicable]

## Validations

- On Save: Validate Dates (as in Print Order)
- On Save: Validate Customer (as in Print Order)
- On Save: Validate Fabric Items (as in Print Order)
- On Save: Validate Process Items (as in Print Order)
- On Save: Fabric Material and Type should be same between Greige Fabric, Ready Fabric
- Before Submit: Process Items Mandatory check (Desizing mandatory check based on settings)
- Before Submit: Set existing BOM (match based on Greige Fabric, Ready Fabric, Process Items, 
- ...

**Comment by abid-omar** [comment]
- Greige Fabric and Ready Fabric GENERALLY have different Width and GSM/Weight
- May not require Sales Order for Greige, as Sales Order will usually be for Printed Fabrics (where pretreatment is just one of the production processes).
- Singeing is also optional, only Bleaching is a mandatory.
- Fabric Details Section to show Ready Fabric parameters (width/gsm etc.)

**Comment by SaiFi0102** [comment]
> * May not require Sales Order for Greige, as Sales Order will usually be for Printed Fabrics (where pretreatment is just one of the production processes).

Sales Order would be needed for tracking customer billing against the pretreatment

**Comment by abid-omar** [comment]
There is the possibility that Pretreatment is done first, and Sales Order generated second.
