### ISSUE TITLE
feat(Pretreatment Order): Integrate with BOM

### ISSUE THREAD

**Issue by SaiFi0102** [ParaLogicTech/textile#54]
## Fabric BOM Heirarchy

Greige Fabric -> Ready Fabric -> Printed Fabric

![Image](https://user-images.githubusercontent.com/328330/258581081-b42a7ade-bbd0-4219-95b6-92409c610136.png)

## Notes

- BOM to be created by Pretreatment Order
- BOM to be reused if already exists. Uniquely identified by their components (Greige Fabric, Ready Fabric, Singeing Process, Bleaching Process, Desizing Process)
- Operations to be tracked separately
- Materials are only backflushed once production is complete or partially complete (operations do not backflush materials)
- 

## Ready Fabric BOM Structure

**Output Qty:** 1 Meter

**Materials**

- Greige Fabric: 1 Meter
- Singeing: 1 Meter ?
- Bleaching: `Greige Fabric Net Weight * Greige Fabric Pickup % / 100` Grams
- Desizing: `Greige Fabric Net Weight * Greige Fabric Pickup % / 100` Grams

## Singeing BOM Structure

Output Qty: 1 Meter

**Materials**

- Gas: `w` Grams

**Singeing Operation**

- Time: `t` Minutes
- Cost: Rs `c` per Hour

## Bleaching BOM Structure

Output Qty: `w0` Grams

**Materials**

- Chemical 1: `w1` Grams
- Chemical 2: `w1` Grams
- RO Water: 1000 Grams

**Bleaching Operation**

- Time: `t` Minutes
- Cost: Rs `c` per Hour

## Desizing BOM Structure

Output Qty: `w0` Grams

**Materials**

- Chemical 1: `w1` Grams
- Chemical 2: `w1` Grams
- RO Water: 1000 Grams

**Desizing Operation**

- Time: `t` Minutes
- Cost: Rs `c` per Hour

**Comment by abid-omar** [comment]
Sequence of operations is
Singeing -> Desizing -> Bleaching

**Comment by abid-omar** [comment]
Last operation "Padding" not needed. Desizing and Bleaching are done on the Padding workstation.
Input/output quantity of fabric is always in meters (from user perspective), but weight is used for the BOM.
