### ISSUE TITLE
feat: Fabric Printing Summary Report

### ISSUE THREAD

**Issue by SaiFi0102** [ParaLogicTech/textile#55]
Could be a report called "Fabric Printing Summary"

Rows can be based on Fabric Material with their totals in multiple columns. With an additional "Total" row for all materials.

**Filters:**

- From Date
- To Date

**Columns:**

- Fabric Material / Total
- No of Orders
- Ordered Qty
- Fabric Received Qty
- Produced Qty
- Packed Qty
- Delivered Qty

Using this report we can add another feature for auto emailing the data by running report twice, one for the month data and another for the 24-hour data and summarize according to what you wrote and send an email at the configured time of day.

## Abid Omar's comments

Subject: [ERP/fabric] Production Report

**xxx/ZZZ Meters Print Orders Received** (YY)
xxx Meters Cotton (YY)
xxx Meters Silk (YY)
xxx Meters Viscose (YY)
xxx Meters Polyester (YY)

xxx/ZZZ Meters Print Orders Packed (YY)
xxx/ZZZ Meters Print Orders Delivered (YY)
xxx/ZZZ Meters Fabric Stock Received (YY)

Comments:
xxx is Meters in 24-hours
YY is number of Orders
ZZZ is Meters in current month
Report sent at 09:00 based on last 24-hours?
If no data, then line item should not be there.
YY and ZZZ can be a gray color?

Same report to include Pretreatment items.

**Comment by abid-omar** [comment]
Add last line that shows most printed item with thumbnail:

Quantity + Fabric name + Design name
Thumbail

**Comment by SaiFi0102** [comment]
Should Packed and Delivered Qty include return qty or not? @abid-omar

**Comment by abid-omar** [comment]
Packed items to include Return Qty
Delivered items to NOT include Return Qty (as that is relevant for billing)

**Comment by abid-omar** [comment]
Will include Pretreatment summary in same email report.
