### ISSUE TITLE
feat: Textile Email Digest

### ISSUE THREAD

**Issue by SaiFi0102** [ParaLogicTech/textile#61]
Split from https://github.com/ParaLogicTech/textile/issues/55

- New Single DocType: Textile Email Digest
- Module: Textile
- Add in Digital Printing Workspace "Settings" section

**Fields**

- Enabled - Checkbox (not enabled by default)
- Receiver - Text field, new-line / comma separated values
- Email Template - Link field
- Do Not Send If No Transactions - Checkbox (checked by default)
- Send at Hour of the Day - Int (0 to 23, 0 by default)

**Functionality**

- Schedule hourly
- Do not send if not enabled
- Do not send if last sent date == Today (store in `frappe.db.set_global`)
- Send only if hour of day >= configured hour of day
- Build context for email: Get Fabric Printing Summary data for Yesterday only (key `daily`)
- Build context for email: Pass Fabric Printing Summary data for 1st of Month till Yesterday (key `monthly`)
- Build context for email: Pass `from_date` (1st of month date) and `to_date` (yesterday date / reporting date)
- Do not send if yesterday data is empty (no transactions) if configured - this will also help with preventing email for holidays
- Do not send if not enabled or no receiver configured or no email template selected
- Send using Email Template
- Validate on save if enabled but no email template or no receiver configured

**Comment by abid-omar** [comment]
Schedule daily (not hourly)

**Comment by SaiFi0102** [comment]
System will send once per day, but will have to run the API hourly to make sure it runs at the configured hour of day. Technically the API will be running hourly, functionally it will send once daily

**Comment by abid-omar** [comment]
Subject: [ERP/fabric] Production Report

**xxx/ZZZ Meters Print Orders Submitted (YY)**
xxx Meters Cotton (YY)
xxx Meters Silk (YY)
xxx Meters Viscose (YY)
xxx Meters Polyester (YY)

**xxx/ZZZ Meters Printed (YY)**
xxx/ZZZ Meters Print Orders Packed (YY)
xxx/ZZZ Meters Print Orders Delivered (YY)
xxx/ZZZ Meters Fabric Stock Received (YY)

Quantity + Fabric name + Design name / xx Meters
Thumbnail (rotated)

Comments:
xxx is Meters in 24-hours
YY is number of Orders
ZZZ is Meters in current month
Report sent at 09:00 based on last 24-hours?
If no data, then line item should not be there.
YY and ZZZ can be a gray color?

Same report to include Pretreatment items.

**Comment by abid-omar** [comment]
Email report format updated to tabular form, and backlog added.

| Order status    | Orders   | Day      | Month    | Backlog  |
| --------------- | -------- | -------- | -------- | -------- |
| Order intake    | n        | xxx      | yyy      | zzz      |
| - Cotton        | n        | xxx      | yyy      | zzz      |
| - Polyester     | n        | xxx      | yyy      | zzz      |
| Printed         | n        | xxx      | yyy      | zzz      |
| Packed          | n        | xxx      | yyy      | zzz      |
| Delivered       | n        | xxx      | yyy      |          |


| Stock                      | Day      | Total    |
| -------------------------- | -------- | -------- |
| Customer fabrics           | zzz      | zzz      |
| Own fabrics                | zzz      | zzz      |

[Thumbnail]
Most produced: zzz Customer, Fabric, Item

n - number of orders (today)
xxx - meters in last 24-hours
yyy - meters in current month
zzz - meters backlog, e.g.
orders submitted (order intake) but not printed
orders printed but not packed
ordered packed but not delivered
